CREATE TABLE TEST_CONTRACT (
    ICONTRACTID int,
    SPROCESSNAME varchar(50),
    SPROCESSINSTANCEID varchar(10),
    ISTATUS int,
    IWFSTATUS int,
    IRETURNFLAG int,
    DSIGNATUREDATE datetime,
    SEFFECTIVEAUDITOR varchar(50),
    primary key(ICONTRACTID)
);


 SELECT COUNT(*) FROM TEST_CONTRACT WHERE SPROCESSINSTANCEID IS NULL;
 
 UPDATE TEST_CONTRACT SET SPROCESSNAME=''; 
 UPDATE TEST_CONTRACT SET SPROCESSINSTANCEID='';
 UPDATE TEST_CONTRACT SET ISTATUS=0;
 UPDATE TEST_CONTRACT SET IWFSTATUS=0;
