
 

CREATE TABLE SYS_ACCESS(
        ROLEID NUMBER(19) NOT NULL,
        APPID NUMBER(19) NOT NULL,
        PRIMARY KEY (ROLEID, APPID)
);


CREATE TABLE SYS_APPLICATION(
        ID NUMBER(19) NOT NULL,
        NAME NVARCHAR2(255),
	CODE NVARCHAR2(255),
        APPDESC NVARCHAR2(255),
        URL NVARCHAR2(255),
        SORT INTEGER,
        SHOWMENU INTEGER,
        NODEID NUMBER(19) NOT NULL,
	locked INTEGER,
        PRIMARY KEY (ID)
);


CREATE TABLE SYS_DEPARTMENT(
        ID NUMBER(19) NOT NULL,
        NAME NVARCHAR2(255),
        DEPTDESC NVARCHAR2(255),
        CREATETIME TIMESTAMP(6),
        SORT INTEGER,
        DEPTNO NVARCHAR2(255),
        CODE NVARCHAR2(255),
        CODE2 NVARCHAR2(255),
        STATUS INTEGER,
        FINCODE NVARCHAR2(255),
        NODEID NUMBER(19) NOT NULL,
        PRIMARY KEY (ID)
);

CREATE TABLE SYS_DEPT_ROLE(
        ID NUMBER(19) NOT NULL,
        GRADE INTEGER,
        CODE NVARCHAR2(255),
        SORT INTEGER,
        SYSROLEID NUMBER(19) NOT NULL,
        DEPTID NUMBER(19) NOT NULL,
        PRIMARY KEY (ID)
);

CREATE TABLE SYS_FUNCTION(
        ID NUMBER(19) NOT NULL,
        NAME NVARCHAR2(255),
        FUNCDESC NVARCHAR2(255),
        FUNCMETHOD NVARCHAR2(255),
        SORT INTEGER,
        APPID NUMBER(19) NOT NULL,
        PRIMARY KEY (ID)
);

CREATE TABLE SYS_LOG(
        ID NUMBER(19) NOT NULL,
        ACCOUNT NVARCHAR2(255),
        IP NVARCHAR2(255),
        CREATETIME TIMESTAMP(6),
        OPERATE NVARCHAR2(255),
        FLAG INTEGER,
        PRIMARY KEY (ID)
);

CREATE TABLE SYS_PERMISSION (
        ROLEID NUMBER(19) NOT NULL,
        FUNCID NUMBER(19) NOT NULL,
        PRIMARY KEY (ROLEID, FUNCID)
 );

CREATE TABLE SYS_ROLE(
        ID NUMBER(19) NOT NULL,
        NAME NVARCHAR2(255),
        ROLEDESC NVARCHAR2(255),
        CODE NVARCHAR2(255),
        SORT INTEGER,
        PRIMARY KEY (ID)
);


CREATE TABLE SYS_TREE (
        ID NUMBER(19) NOT NULL,
        PARENT NUMBER(19),
        NAME NVARCHAR2(255),
        NODEDESC NVARCHAR2(255),
	CACHEFLAG NVARCHAR2(1),
	DISCRIMINATOR NVARCHAR2(1),
	MOVEABLE NVARCHAR2(1),
	TREEID NVARCHAR2(200),
        SORT INTEGER,
        CODE NVARCHAR2(255),
	ICON NVARCHAR2(255),
	ICONCLS NVARCHAR2(255),
	URL NVARCHAR2(255),
	LOCKED INTEGER DEFAULT 0,
        PRIMARY KEY (ID)
);

CREATE TABLE SYS_USER (
        ID NUMBER(19) NOT NULL,
        ACCOUNT NVARCHAR2(255),
        PASSWORD NVARCHAR2(255),
        CODE NVARCHAR2(255),
        NAME NVARCHAR2(255),
        BLOCKED INTEGER,
        CREATETIME TIMESTAMP(6),
        LASTLOGINTIME TIMESTAMP(6),
        LASTLOGINIP NVARCHAR2(255),
        EVECTION INTEGER,
        MOBILE NVARCHAR2(255),
        EMAIL NVARCHAR2(255),
        TELEPHONE NVARCHAR2(255),
        GENDER INTEGER,
        HEADSHIP NVARCHAR2(255),
        USERTYPE INTEGER,
        FAX NVARCHAR2(255),
        ACCOUNTTYPE INTEGER,
        DUMPFLAG INTEGER,
        DEPTID NUMBER(19),
	ADMINFLAG NVARCHAR2(1),
	SUPERIORIDS NVARCHAR2(200),
        PRIMARY KEY (ID)
);

CREATE TABLE SYS_USER_ROLE(
        ID NUMBER(19) NOT NULL,
        USERID NUMBER(19) DEFAULT 0,
        ROLEID NUMBER(19) DEFAULT 0,
        AUTHORIZED INTEGER DEFAULT 0,
        AUTHORIZEFROM NUMBER(19) DEFAULT 0,
        AVAILDATESTART TIMESTAMP(6),
        AVAILDATEEND TIMESTAMP(6),
        PROCESSDESCRIPTION NVARCHAR2(255),
        PRIMARY KEY (ID)
);

CREATE TABLE SYS_DICTORY (
        ID NUMBER(19) NOT NULL,
        TYPEID NUMBER(19),
        NAME NVARCHAR2(50),
        DICTDESC NVARCHAR2(200),
        CODE NVARCHAR2(50),
	VALUE_ NVARCHAR2(2000),
        SORT INTEGER,
        BLOCKED INTEGER,
        EXT1 NVARCHAR2(200),
        EXT2 NVARCHAR2(200),
        EXT3 NVARCHAR2(200),
        EXT4 NVARCHAR2(200),
        EXT5 TIMESTAMP(6),
        EXT6 TIMESTAMP(6),
        EXT7 TIMESTAMP(6),
        EXT8 TIMESTAMP(6),
        EXT9 TIMESTAMP(6),
        EXT10 TIMESTAMP(6),
        EXT11 NUMBER(19,0),
        EXT12 NUMBER(19,0),
        EXT13 NUMBER(19,0),
        EXT14 NUMBER(19,0),
        EXT15 NUMBER(19,0),
        EXT16 NUMBER(*,10),
        EXT17 NUMBER(*,10),
        EXT18 NUMBER(*,10),
        EXT19 NUMBER(*,10),
        EXT20 NUMBER(*,10),
        PRIMARY KEY (ID)
);

CREATE TABLE SYS_DICTORY_DEF (
        ID NUMBER(19) NOT NULL,
        NODEID NUMBER(19),
        NAME NVARCHAR2(50),
        COLUMNNAME NVARCHAR2(50),
        TITLE NVARCHAR2(50),
        TYPE NVARCHAR2(50),
        LENGTH INTEGER,
        SORT INTEGER,
        REQUIRED INTEGER,
        TARGET NVARCHAR2(50),
        PRIMARY KEY (ID)
);

CREATE TABLE SYS_WORKCALENDAR (
        ID NUMBER(19) NOT NULL,
        FREEDAY INTEGER,
        FREEMONTH INTEGER,
        FREEYEAR INTEGER,
        PRIMARY KEY (ID)
);


CREATE TABLE SYS_TODO(
        ID NUMBER(19) NOT NULL,
        CODE NVARCHAR2(255),
        CONTENT NVARCHAR2(255),
        DEPTID NUMBER(19),
        DEPTNAME NVARCHAR2(255),
        ENABLEFLAG INTEGER,
        LIMITDAY INTEGER,
        XA INTEGER,
        XB INTEGER,
        LINK NVARCHAR2(255),
        LISTLINK NVARCHAR2(255),
	ALLLISTLINK NVARCHAR2(255),
        LINKTYPE NVARCHAR2(255),
        APPID NUMBER(19),
        MODULEID NUMBER(19),
        MODULENAME NVARCHAR2(255),
        OBJECTID NVARCHAR2(255),
        OBJECTVALUE NVARCHAR2(255),
        PROCESSNAME NVARCHAR2(255),
        ROLECODE NVARCHAR2(255),
        ROLEID NUMBER(19),
        TASKNAME NVARCHAR2(255),
        TITLE NVARCHAR2(255),
        TYPE NVARCHAR2(50),
	PROVIDER NVARCHAR2(50),
        SQL_ NVARCHAR2(2000),
	SORTNO INTEGER,
        VERSIONNO NUMBER(19),
        PRIMARY KEY (ID)
    );

CREATE TABLE SYS_TODO_INSTANCE(
        ID NUMBER(19) NOT NULL,
        ACTORID NVARCHAR2(255),
        ACTORNAME NVARCHAR2(255),
        TITLE NVARCHAR2(255),
        CONTENT NVARCHAR2(255),
        PROVIDER NVARCHAR2(255),
        LINK_ NVARCHAR2(255),
        LINKTYPE NVARCHAR2(255),
        CREATEDATE TIMESTAMP(6),
        STARTDATE TIMESTAMP(6),
        ENDDATE TIMESTAMP(6),
        ALARMDATE TIMESTAMP(6),
        PASTDUEDATE TIMESTAMP(6),
        TASKINSTANCEID NVARCHAR2(255),
        PROCESSINSTANCEID NVARCHAR2(255),
        DEPTID NUMBER(19),
        DEPTNAME NVARCHAR2(255),
        ROLEID NUMBER(19),
        ROLECODE NVARCHAR2(255),
        ROWID_ NVARCHAR2(255),
        TODOID NUMBER(19),
        APPID NUMBER(19),
        MODULEID NUMBER(19),
        OBJECTID NVARCHAR2(255),
        OBJECTVALUE NVARCHAR2(255),
        VERSIONNO NUMBER(19),
        PRIMARY KEY (ID)
    );

  CREATE TABLE SYS_SCHEDULER (
        ID NVARCHAR2(50)  NOT NULL,
	AUTOSTARTUP INTEGER,
        CREATEBY NVARCHAR2(255),
        CREATEDATE TIMESTAMP(6),
	TITLE NVARCHAR2(200),
        CONTENT NVARCHAR2(500),
	STARTDATE TIMESTAMP(6),
        ENDDATE TIMESTAMP(6),
        EXPRESSION_ NVARCHAR2(500),
        JOBCLASS NVARCHAR2(200),
        LOCKED_ INTEGER,
        PRIORITY_ INTEGER,
        REPEATCOUNT INTEGER,
        REPEATINTERVAL INTEGER,
        STARTDELAY INTEGER,
        STARTUP_ INTEGER,
        TASKNAME NVARCHAR2(200),
        TASKTYPE NVARCHAR2(50),
        THREADSIZE INTEGER,
	ATTRIBUTE_ NVARCHAR2(500),
        PRIMARY KEY (ID)
    );

CREATE TABLE MESSAGE(
        ID NUMBER(19) NOT NULL,
        TYPE INTEGER,
        SYSTYPE INTEGER,
        SENDER NUMBER(19),
        RECVER NUMBER(19),
        RECVERLIST NVARCHAR2(2000) ,
        TITLE NVARCHAR2(500) ,
        CONTENT NVARCHAR2(2000) ,
        CREATEDATE TIMESTAMP(6),
        READED INTEGER,
        CATEGORY INTEGER,
        CRUSER NVARCHAR2(20),
        CRDATE TIMESTAMP(6),
        EDUSER NVARCHAR2(20),
        EDDATE TIMESTAMP(6),
        PRIMARY KEY (ID)
  );

CREATE TABLE MYMENU(
        ID NUMBER(19) NOT NULL,
        USERID NUMBER(19),
        TITLE NVARCHAR2(100),
        URL NVARCHAR2(200),
        SORT INTEGER,
        CRUSER NVARCHAR2(20),
        CRDATE TIMESTAMP(6),
        EDUSER NVARCHAR2(20),
        EDDATE TIMESTAMP(6),
        PRIMARY KEY (ID)
);

CREATE TABLE SUBJECTCODE(
        ID NUMBER(19) NOT NULL ,
        PARENT NUMBER(19),
        SUBJECTCODE NVARCHAR2(20),
        SUBJECTNAME NVARCHAR2(100),
        FEESUM NUMBER(*,10) ,
        MONTH1 NUMBER(*,10) ,
        MONTH2 NUMBER(*,10) ,
        MONTH3 NUMBER(*,10) ,
        MONTH4 NUMBER(*,10) ,
        MONTH5 NUMBER(*,10) ,
        MONTH6 NUMBER(*,10) ,
        MONTH7 NUMBER(*,10) ,
        MONTH8 NUMBER(*,10) ,
        MONTH9 NUMBER(*,10) ,
        MONTH10 NUMBER(*,10) ,
        MONTH11 NUMBER(*,10) ,
        MONTH12 NUMBER(*,10) ,
        FEEYEAR INTEGER ,
        SORT INTEGER ,
        PRIMARY KEY (ID)
    );


CREATE TABLE  ATTACHMENT (
	ID NUMBER(19)  NOT NULL ,
	REFERID NUMBER(19)  ,
	REFERTYPE INTEGER  ,
	NAME NVARCHAR2 (100)   ,
	URL NVARCHAR2 (200)   ,
	CREATEDATE TIMESTAMP(6)  ,
	CREATEID NUMBER(19)  ,
	CRUSER NVARCHAR2 (20)   ,
	CRDATE TIMESTAMP(6)  ,
	EDUSER NVARCHAR2 (20)   ,
	EDDATE TIMESTAMP(6) ,
	PRIMARY KEY (ID)
);


  CREATE TABLE  MyAudit (
	ID NUMBER(19) NOT NULL ,
	REFERID NUMBER(19) ,
	REFERTYPE INTEGER ,
	DEPTID NUMBER(19) ,
	DEPTNAME NVARCHAR2 (50) ,
	HEADSHIP NVARCHAR2 (100) ,
	LEADERNAME NVARCHAR2 (100) ,
	LEADERID NUMBER(19) ,
	CREATEDATE TIMESTAMP(6) ,
	MEMO NVARCHAR2 (2000) ,
	FLAG INTEGER ,
	CRUSER NVARCHAR2 (20) ,
	CRDATE TIMESTAMP(6) ,
	EDUSER NVARCHAR2 (20) ,
	EDDATE TIMESTAMP(6) , 
	PRIMARY KEY (ID)
);

CREATE TABLE SYS_DBID(
        NAME_ NVARCHAR2(50)  NOT NULL,
	TITLE_ NVARCHAR2(255),
        VALUE_ NVARCHAR2(255) NOT NULL,
        VERSION_ INTEGER NOT NULL,
        PRIMARY KEY (NAME_)
);

CREATE TABLE SYS_AGENT (
        ID_ NVARCHAR2(50)  NOT NULL,
        AGENTTYPE_ INTEGER,
        ASSIGNFROM_ NVARCHAR2(255) ,
        ASSIGNTO_ NVARCHAR2(255) ,
        CREATEDATE_ TIMESTAMP(6),
        ENDDATE_ TIMESTAMP(6),
        LOCKED_ INTEGER,
        OBJECTID_ NVARCHAR2(255) ,
        OBJECTVALUE_ NVARCHAR2(255) ,
        PROCESSNAME_ NVARCHAR2(255) ,
        SERVICEKEY_ NVARCHAR2(50) ,
        STARTDATE_ TIMESTAMP(6),
        TASKNAME_ NVARCHAR2(255) ,
        PRIMARY KEY (ID_)
 );

CREATE TABLE SYS_PROPERTY (
        ID_ NVARCHAR2(50) NOT NULL,
        CATEGORY_ NVARCHAR2(200),
        DESCRIPTION_ NVARCHAR2(500),
        INITVALUE_ NVARCHAR2(1000),
        LOCKED_ INTEGER,
        NAME_ NVARCHAR2(50),
        TITLE_ NVARCHAR2(200),
        TYPE_ NVARCHAR2(50),
        VALUE_ NVARCHAR2(1000),
        PRIMARY KEY (ID_)
);


    create index IDX_USER_ACCOUNT on SYS_USER (ACCOUNT);

    create index IDX_USER_NAME on SYS_USER (NAME);

    create index IDX_TREE_NAME on SYS_TREE (NAME);

    create index IDX_TREE_CODE on SYS_TREE (CODE);

    create index IDX_ROLE_NAME on SYS_ROLE (NAME);

    create index IDX_ROLE_CODE on SYS_ROLE (CODE);

    create index SYS_DEPT_NAME on SYS_DEPARTMENT (NAME);

    create index SYS_DEPT_CODE on SYS_DEPARTMENT (CODE);

    create index SYS_DEPT_NODE on SYS_DEPARTMENT (NODEID);

    create index SYS_APP_NAME on SYS_APPLICATION (NAME);

    create index SYS_APP_CODE on SYS_APPLICATION (CODE);

    create index SYS_APP_NODE on SYS_APPLICATION (NODEID);

    create index SYS_DEPTROLE_DEPT on SYS_DEPT_ROLE (DEPTID);

    create index SYS_DEPTROLE_ROLE on SYS_DEPT_ROLE (SYSROLEID);

    create index SYS_USERROLE_ROLE on SYS_USER_ROLE (ROLEID);

    create index SYS_USERROLE_USER on SYS_USER_ROLE (USERID);

    alter table SYS_ACCESS 
        add constraint FK_ACCESS_APP 
        foreign key (APPID) 
        references SYS_APPLICATION;

    alter table SYS_ACCESS 
        add constraint FK_ACCESS_DEPTROLE 
        foreign key (ROLEID) 
        references SYS_DEPT_ROLE;

    alter table SYS_APPLICATION 
        add constraint FK_APP_TREE 
        foreign key (NODEID) 
        references SYS_TREE;

    alter table SYS_DEPARTMENT 
        add constraint FK_DEPT_TREE 
        foreign key (NODEID) 
        references SYS_TREE;

    alter table SYS_DEPT_ROLE 
        add constraint FK_DEPTROLE_DEPT 
        foreign key (DEPTID) 
        references SYS_DEPARTMENT;

    alter table SYS_DEPT_ROLE 
        add constraint FK_DEPTROLE_ROLE 
        foreign key (SYSROLEID) 
        references SYS_ROLE;

    alter table SYS_FUNCTION 
        add constraint FK_FUN_APP 
        foreign key (APPID) 
        references SYS_APPLICATION;

    alter table SYS_PERMISSION 
        add constraint FK_PERM_DEPTROLE 
        foreign key (ROLEID) 
        references SYS_DEPT_ROLE;

    alter table SYS_PERMISSION 
        add constraint FK_PERM_FUN
        foreign key (FUNCID) 
        references SYS_FUNCTION;

    alter table SYS_USER 
        add constraint FK_USER_DEPT 
        foreign key (DEPTID) 
        references SYS_DEPARTMENT;

    alter table SYS_USER_ROLE 
        add constraint FK_USERROLE_ROLE 
        foreign key (ROLEID) 
        references SYS_DEPT_ROLE;

    alter table SYS_USER_ROLE 
        add constraint FK_USERROLE_USER 
        foreign key (USERID) 
        references SYS_USER;