
CREATE TABLE UI_LAYOUT(
        ID_ VARCHAR(50) NOT NULL,
        ACTORID_ VARCHAR(255),
        COLUMNSTYLE_ VARCHAR(255),
        COLUMNS_ INTEGER,
        CREATEDATE_ TIMESTAMP,
        DATAINDEX_ INTEGER,
        NAME_ VARCHAR(50) NOT NULL,
        PANELS_ VARCHAR(255),
        SPACESTYLE_ VARCHAR(50),
        TEMPLATEID_ VARCHAR(50),
        TITLE_ VARCHAR(255),
        PRIMARY KEY (ID_)
 );


 CREATE TABLE UI_PANEL (
        ID_ VARCHAR(50) NOT NULL,
        ACTORID_ VARCHAR(255),
        CLOSE_ INTEGER,
        COLLAPSIBLE_ INTEGER,
        COLOR_ VARCHAR(50),
        COLUMNINDEX_ INTEGER,
        CONTENT_ CLOB,
        CREATEDATE_ TIMESTAMP,
        HEIGHT_ INTEGER,
        ICON_ VARCHAR(255),
        LINK_ VARCHAR(200),
        LOCKED_ INTEGER,
        MODULEID_ VARCHAR(255),
        MODULENAME_ VARCHAR(255),
        MORELINK_ VARCHAR(200),
        NAME_ VARCHAR(50) NOT NULL,
        QUERYID_ VARCHAR(200),
        RESIZE_ INTEGER,
        STYLE_ VARCHAR(200),
        TITLE_ VARCHAR(255),
        TYPE_ VARCHAR(20),
        WIDTH_ INTEGER,
        PRIMARY KEY (ID_)
);


CREATE TABLE UI_PANELINSTANCE (
        ID_ VARCHAR(50) NOT NULL,
        NAME_ VARCHAR(50),
        PANEL_ VARCHAR(50),
        USERPANEL_ VARCHAR(50),
        PRIMARY KEY (ID_)
);

CREATE TABLE UI_SKIN (
        ID_ VARCHAR(50) NOT NULL,
        CREATEDATE_ TIMESTAMP,
        DESCRIPTION_ VARCHAR(500),
        IMAGE_ VARCHAR(255),
        LOCKED_ INTEGER NOT NULL,
        NAME_ VARCHAR(50) NOT NULL,
        STYLECLASS_ VARCHAR(255),
        TITLE_ VARCHAR(255),
        PRIMARY KEY (ID_)
);

CREATE TABLE UI_SKININSTANCE (
        ID_ VARCHAR(50) NOT NULL,
        ACTORID_ VARCHAR(255),
        SKIN_ VARCHAR(50),
        PRIMARY KEY (ID_)
);

CREATE TABLE UI_USERPANEL (
        ID_ VARCHAR(50) NOT NULL,
        ACTORID_ VARCHAR(50),
        CREATEDATE_ TIMESTAMP,
        LAYOUTNAME_ VARCHAR(20),
        REFRESHSECONDS_ INTEGER,
        LAYOUT_ VARCHAR(50),
        PRIMARY KEY (ID_)
);

CREATE TABLE UI_USERPORTAL (
        ID_ VARCHAR(50) NOT NULL,
        ACTORID_ VARCHAR(50),
        COLUMNINDEX_ INTEGER,
        CREATEDATE_ TIMESTAMP,
        PANELID_ VARCHAR(50),
        POSITION_ INTEGER,
        PRIMARY KEY (ID_)
);

