
 create table EX_JBPM_ACTIVITY_INSTANCE ( 
    ID_ NUMBER(19,0)  not null ,
    ACTORID_ NVARCHAR2  (50) ,
    PROCESSINSTANCEID_ NUMBER(19,0) ,
    TASKINSTANCEID_ NUMBER(19,0) ,
    TASKNAME_ NVARCHAR2  (50) ,
    TASKDESCRIPTION_ NVARCHAR2  (200) ,
    OBJECTID_ NVARCHAR2  (200) ,
    OBJECTVALUE_ NVARCHAR2  (200) ,
    ROWID_ NVARCHAR2  (50) ,
    TITLE_ NVARCHAR2  (100) ,
    ISAGREE_ NVARCHAR2  (20) ,
    CONTENT_ NVARCHAR2  (1000) ,
    VARIABLE_ NVARCHAR2  (1000) ,
    DATE_ TIMESTAMP(6) ,
    PREVIOUSACTORS_ NVARCHAR2  (500) ,
    primary key (ID_) 
);


 create table EX_JBPM_CONFIGFILE ( 
    ID_ NUMBER(19,0)  not null ,
    FILENAME_ NVARCHAR2  (200) ,
    LASTMODIFIED_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table EX_JBPM_EXFIELD ( 
    ID_ NUMBER(19,0)  not null ,
    EXTENDID_ NVARCHAR2  (100) ,
    NAME_ NVARCHAR2  (50) ,
    VALUE_ NVARCHAR2  (2000) ,
    EXTENSION_ NUMBER(19,0) ,
    primary key (ID_) 
);


 create table EX_JBPM_EXPARAM ( 
    ID_ NUMBER(19,0)  not null ,
    EXTENDID_ NVARCHAR2  (100) ,
    NAME_ NVARCHAR2  (50) ,
    TYPE_ NVARCHAR2  (50) ,
    VALUE_ NVARCHAR2  (2000) ,
    EXTENSION_ NUMBER(19,0) ,
    PARAMCOLLECTIONINDEX_ INTEGER ,
    primary key (ID_) 
);


 create table EX_JBPM_EXTENSION ( 
    ID_ NUMBER(19,0)  not null ,
    EXTENDID_ NVARCHAR2  (100) ,
    NAME_ NVARCHAR2  (50) ,
    TYPE_ NVARCHAR2  (50) ,
    DESCRIPTION_ NVARCHAR2  (200) ,
    PROCESSNAME_ NVARCHAR2  (50) ,
    TASKNAME_ NVARCHAR2  (50) ,
    OBJECTID_ NVARCHAR2  (50) ,
    OBJECTVALUE_ NVARCHAR2  (255) ,
    LOCKED_ INTEGER ,
    CREATEDATE_ TIMESTAMP(6) ,
    CREATEACTORID_ NVARCHAR2  (255) ,
    UPDATEDATE_ TIMESTAMP(6) ,
    UPDATEACTORID_ NVARCHAR2  (255) ,
    primary key (ID_) 
);

