
CREATE TABLE UI_LAYOUT(
        ID_ NVARCHAR2(50) NOT NULL,
        ACTORID_ NVARCHAR2(255),
        COLUMNSTYLE_ NVARCHAR2(255),
        COLUMNS_ INTEGER,
        CREATEDATE_ TIMESTAMP(6),
        DATAINDEX_ INTEGER,
        NAME_ NVARCHAR2(50) NOT NULL,
        PANELS_ NVARCHAR2(255),
        SPACESTYLE_ NVARCHAR2(50),
        TEMPLATEID_ NVARCHAR2(50),
        TITLE_ NVARCHAR2(255),
        PRIMARY KEY (ID_)
 );


 CREATE TABLE UI_PANEL (
        ID_ NVARCHAR2(50) NOT NULL,
        ACTORID_ NVARCHAR2(255),
        CLOSE_ INTEGER,
        COLLAPSIBLE_ INTEGER,
        COLOR_ NVARCHAR2(50),
        COLUMNINDEX_ INTEGER,
        CONTENT_ CLOB,
        CREATEDATE_ TIMESTAMP(6),
        HEIGHT_ INTEGER,
        ICON_ NVARCHAR2(255),
        LINK_ NVARCHAR2(200),
        LOCKED_ INTEGER,
        MODULEID_ NVARCHAR2(255),
        MODULENAME_ NVARCHAR2(255),
        MORELINK_ NVARCHAR2(200),
        NAME_ NVARCHAR2(50) NOT NULL,
        QUERYID_ NVARCHAR2(200),
        RESIZE_ INTEGER,
        STYLE_ NVARCHAR2(200),
        TITLE_ NVARCHAR2(255),
        TYPE_ NVARCHAR2(20),
        WIDTH_ INTEGER,
        PRIMARY KEY (ID_)
);


CREATE TABLE UI_PANELINSTANCE (
        ID_ NVARCHAR2(50) NOT NULL,
        NAME_ NVARCHAR2(50),
        PANEL_ NVARCHAR2(50),
        USERPANEL_ NVARCHAR2(50),
        PRIMARY KEY (ID_)
);

CREATE TABLE UI_SKIN (
        ID_ NVARCHAR2(50) NOT NULL,
        CREATEDATE_ TIMESTAMP(6),
        DESCRIPTION_ NVARCHAR2(500),
        IMAGE_ NVARCHAR2(255),
        LOCKED_ INTEGER NOT NULL,
        NAME_ NVARCHAR2(50) NOT NULL,
        STYLECLASS_ NVARCHAR2(255),
        TITLE_ NVARCHAR2(255),
        PRIMARY KEY (ID_)
);

CREATE TABLE UI_SKININSTANCE (
        ID_ NVARCHAR2(50) NOT NULL,
        ACTORID_ NVARCHAR2(255),
        SKIN_ NVARCHAR2(50),
        PRIMARY KEY (ID_)
);

CREATE TABLE UI_USERPANEL (
        ID_ NVARCHAR2(50) NOT NULL,
        ACTORID_ NVARCHAR2(50),
        CREATEDATE_ TIMESTAMP(6),
        LAYOUTNAME_ NVARCHAR2(20),
        REFRESHSECONDS_ INTEGER,
        LAYOUT_ NVARCHAR2(50),
        PRIMARY KEY (ID_)
);

CREATE TABLE UI_USERPORTAL (
        ID_ NVARCHAR2(50) NOT NULL,
        ACTORID_ NVARCHAR2(50),
        COLUMNINDEX_ INTEGER,
        CREATEDATE_ TIMESTAMP(6),
        PANELID_ NVARCHAR2(50),
        POSITION_ INTEGER,
        PRIMARY KEY (ID_)
);

